### ISSUE TITLE
automatic generation from user config

### ISSUE THREAD

**Issue by colemickens** [karimould/zellij-forgot#3]
I was told in the Zellij matrix room that a plugin can access the current keybindings.

>The keybinding config is actually available to plugins, but it's hidden somewhat for legacy reasons. It can be accessed through the ModeUpdate event (that's how the status-bar gets th einfo)

So I think you can get this information instead of requiring the user to repeat it. It would be great to have, thanks!

**Comment by karimould** [comment]
Ah nice, i will look into it when I have some free time over the next weeks.

Thank you for the suggestion :-)

**Comment by karimould** [comment]
tried to add it with
https://github.com/karimould/zellij-forgot/pull/4

its not perfect but it works :-).

Thank you again for the suggestion!

If I have some more time i try to clean it up and make it better.
