### ISSUE TITLE
Show mode for auto-generated key bindings 

### ISSUE THREAD

**Issue by akhilman** [karimould/zellij-forgot#6]
Currently, an auto-generated key list shows bindings from the all modes, without mentioning which mode is required for a particular binding to work.

It would be nice to prefix each binding with the list of modes required to access it.

**Comment by karimould** [comment]
thx for the request.

I added the mode here
https://github.com/karimould/zellij-forgot/releases/tag/0.4.0

I need to do some refactoring to make it look pretty :-)

I want to show the keybinds in a scrollable table, but I dont have the time right now.

Thx again.
